### ISSUE TITLE
[Lynnvander_13_MH] ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10574]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | josh.derksen@gmail.com |
| Error Log | [59037 bytes](https://vassalengine.org/files/gh/65479f0d0266d35dd6ca9132bf2bce6b8557ca46) |

<pre>Created a new default board setup using a variety of spacer board (blank boards with pixel dimensions), some as narrow as 1x1050) while a game was open.

Lynnvander_13_MH v0.1 3.5.8

java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
 at VASSAL.build.module.Map.getLocation(Map.java:2417)
 at VASSAL.build.module.Map.getLocation(Map.java:2397)
 at VASSAL.build.module.Map.drawBoardsInRegion(Map.java:2059)
 at VASSAL.build.module.Map.paintRegion(Map.java:2040)
</pre>

**Comment by Cattlesquat** [comment]
This bug happens every now and then. 

I speculate that if we changed the two "if" statements to "while" in this method in BoardPicker, that might get rid of this problem. Because there are relatively-very-few places where the "relative position" information is access/changed, and that's the information that's getting set to out-of-bound indices.

I don't have a repro case though, so it's just speculation.

```
  public void setBoards(Collection<Board> c) {
    reset();
    for (final Board b : c) {
      if (b.relativePosition().x > nx - 1)
        addColumn();
      if (b.relativePosition().y > ny - 1)
        addRow();
    }
    for (final Board b : c) {
      getSlot(b.relativePosition().x + nx * b.relativePosition().y).setBoard(b);
    }
  }

```
