### ISSUE TITLE
Sound suppression in Global Key Commands

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#10822]
Global Key Commands allow downstream reporting to be suppressed. A similar requirements exists with Sound. The issue is exacerbated by limitations in sound handling that can result in unreliable sound (multiple .wav) or additive volume (multiple .mp3). The current workaround requires additional traits and logic by which the GKC can prevent sound traits from firing.

This request is for a checkbox like the "Suppress individual reports" checkbox that would instead "Suppress individual sounds".

This is envisaged as a way of providing module developers with a more reliable and familiar method to suppress multiple sounds, giving them more control using another method to generate the sound they might require for the GKC action.

Forum thread [here](https://forum.vassalengine.org/t/sound-suppression-in-gkc/72719).

**Comment by Cattlesquat** [comment]
Adding a new checkbox would have to wait for 3.7 as it's too late for 3.6 to add new fields to traits. 

I suppose it would be possible to make the *existing* checkbox also suppress sounds, but I'm not sure whether that's really a good idea since it would be kind of a hidden retro-change that doesn't 100% follow from the logic of the original checkbox.

**Comment by riverwanderer** [comment]
I thought of that too; existing checkbox would make a kind of sense but would need a compatibility Global Option to ensure no legacy impact, which I guess would also fall foul of Vassal main version rules.
