### ISSUE TITLE
Virus detection in uninst.exe

### ISSUE THREAD

**Issue by keiranhalcyon31** [vassalengine/vassal#10946]
FYI, Avira is detecting ADWARE/CrossRider.Gen7 in v3.6.2's uninst.exe and moving it to quarantine. It then goes berserk and moves the entire VASSAL installation to quarantine.  I'm working with Avira to get correct exception settings, but it would be nice if it didn't trip anything in the first place. (I'm assuming it's a false-positive.)

**Comment by uckelman** [comment]
We can't do anything about it without knowing what Avira is detecting, first of all. But since everything we package is something which is there intentionally and isn't a virus or malware, I'm not sure what we could do even if we knew. (A common mistake AV programs make is detecting NSIS installers and uninstallers. A lot of malware uses NSIS just because NSIS is a ubiquitous installer/uninstaller package.)

I'd like to know what you hear back from them.

**Comment by keiranhalcyon31** [comment]
Unfortunately, after sending them the file, this is what I got back:

"The analysis you requested is now complete:

<empty message>"

I think I've got the necessary exceptions in place now, though, so it isn't blocking me anymore.  Sorry for the hassle.

**Comment by uckelman** [comment]
It's no hassle. I appreciate being kept apprised of these things, even if there's ultimately nothing we can do about it.
