### ISSUE TITLE
[Undaunted - Normandy] IllegalStateException: No state for Decorator=hideCmd;Hidden In Hand;Hide;{CurrentMap=="USA Hand" || CurrentMap=="GER Hand"};68\,715,71\,715,57377\,0\,Setup

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11058]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter | alvest@brakiri.com |
| Error Log | [11102 bytes](https://vassalengine.org/files/gh/1dcd9fab26cdaa3830f68aabaf2ed64882330068) |

<pre>Selecting a scenario

Undaunted - Normandy v1.0 3.6.3

java.lang.IllegalStateException: No state for Decorator=hideCmd;Hidden In Hand;Hide;{CurrentMap=="USA Hand" || CurrentMap=="GER Hand"};68\,715,71\,715,57377\,0\,Setup
 at VASSAL.counters.Decorator.setState(Decorator.java:348)
 at VASSAL.counters.Decorator.setState(Decorator.java:345)
 at VASSAL.counters.Decorator.setState(Decorator.java:345)
 at VASSAL.counters.Decorator.setState(Decorator.java:345)
</pre>

**Comment by Cattlesquat** [comment]
The errorlog *looks* like what happens when a saved game made with an earlier version of the module is loaded. But weirdly it isn't showing the full stack dump -- e.g. what called the saved game. 

User's text says he was loading a scenario. I tried doing the same thing several w/ the version of the module posted on our site, but this problem didn't reproduce.

Possibly user altered the module but didn't refresh the scenario before loading it?
