### ISSUE TITLE
Infinite recursion with mat as cargo of another mat

### ISSUE THREAD

**Issue by assaultdoor** [vassalengine/vassal#11860]
I'm using Vassal 3.6.9 on MacOS.

I'd like to have a large mat with some smaller mats on top of it. However, the first time I tried, I get an uncaught exception and this in the error log:

ERROR VASSAL.tools.ErrorDialog - java.lang.StackOverflowError: null
        at VASSAL.counters.Mat.getLocalizedProperty(Mat.java:345)
        at VASSAL.counters.Decorator.getLocalizedProperty(Decorator.java:202)
        at VASSAL.counters.DynamicProperty.getLocalizedProperty(DynamicProperty.java:166)
        at VASSAL.counters.MatCargo.getLocalizedProperty(MatCargo.java:582)
        at VASSAL.counters.Decorator.getLocalizedProperty(Decorator.java:202)
Those last five lines repeat for a while.

To replicate:
1) Create a piece A with the Mat property.
2) Create a piece B with the Mat Cargo property, and the Mat property.
3) Put B onto A.
Expected result: you have a mat on a mat
Actual result: you have a mat on a mat and an uncaught exception.

Mat names seem to have nothing to do with it. The error happens whether the two Mat properties have the same mat name or not.

**Comment by BrentEaston** [comment]
@Cattlesquat I presume this is something we will not support for all sorts of reasons. Can we stop it? Or just trap the recursion and report it?

**Comment by Cattlesquat** [comment]
@BrentEaston Hmmm--eek! Yes that's definitely not something we support. Might have to think about the right strategy to trap for this (eg I wonder if there are *other* horrifying opportunities for recursion)

**Comment by Cattlesquat** [comment]
@BrentEaston I'm kind of stumped as to a decent place to trap for, check for, etc, this problem. Putting some kind of recursion checking in the getProperty sequence sounds unattractive. Putting a check *every time* a cargo checks what mat it's on (to make sure the cargo itself isn't a mat) doesn't sounds attractive. We don't have a "validate" path for pieces themselves. Etc. Any ideas?

**Comment by BrentEaston** [comment]
Hi @assaultdoor,

Due to the way Mats and Cargo are implemented (primarily due to the manipulation of the Does Not Stack property), it just isn't possible to implement Mats that are also Cargo.  We are just trying to work out a clean way to prevent this issue from happening.

Ideally, we would prevent you from adding both the Mat and Cargo trait to a piece, but there is no easy way to do this, as they may come in from prototypes.

We could just trap and report the infinite recursion, but that's a bit of a sledgehammer approach.

I think the better way is to say that Mat trumps Cargo, so every Cargo trait will need to check if it's piece also has a Mat trait and 'turn itself off' in this case. @Cattlesquat, we should be able to cache this, so it only happens once.

**Comment by Cattlesquat** [comment]
I could not think of a non-grotesque way to have Mat / Mat Cargo turn itself off, so I instead settled for putting "Bad Data Warnings" in the window when this is discovered during building a piece -- so at least a decent warning to the unwary before the infinite loop comes.
