### ISSUE TITLE
Trigger Action's loop a fixed number of times always happen at least once

### ISSUE THREAD

**Issue by assaultdoor** [vassalengine/vassal#11880]
If a Trigger Action is told to repeat a certain number of times, it will always happen at least once even if told to repeat zero times.

Steps to reproduce:
1) Create a piece.
2) Give it a Report Action
3) Give it a Trigger Action that issues the Report Action's Key Command
4) Click "Repeat this set of Key Commands (Loop)"
5) Set the type of loop to "Repeat fixed number of times"
6) Enter 0 for the number of times
7) Start the game and activate the Trigger Action
Expected result: no reports
Actual result: a report

Unlike the Repeat until condition (which, I assume, is based on C/C++/Java's do-while loops rather than other languages' until loops), this behavior is not documented in the reference manual. I assume zero meaning one is unintended, as it would let me reduce the number of Trigger Actions that exist only to maybe activate other Trigger Actions.

**Comment by Cattlesquat** [comment]
Should be fixed by #11973 

By the way, a counted loop set to execute 0 times WILL execute the "do this before loop" and "do this after loop" keys. That seems... right to me?

@assaultdoor if you happen to notice this, would you mind giving it a test when a build labeled 11880 comes up at vassalengine.org/builds (should be up about 20 minutes after I write this)? You can install with "custom install" and retain your normal version of Vassal.

**Comment by riverwanderer** [comment]
"By the way, a counted loop set to execute 0 times WILL execute the "do this before loop" and "do this after loop" keys. That seems... right to me?"    

Turns out that is consistent with what happens with the "While...." option.

**Comment by assaultdoor** [comment]
I think it works! Thanks.

I agree that "do before" and "do after" should execute even if the loop itself doesn't. That lets me use one trigger to always do one thing and conditionally do others.

**Comment by Cattlesquat** [comment]
Excellent, thanks! This should appear in the next VASSAL release then -- either 3.6.12 or 3.7.0 depending on what happens.
