### ISSUE TITLE
Implement 'Game/Scenario' Preferences

### ISSUE THREAD

**Issue by BrentEaston** [vassalengine/vassal#11932]
Game preferences are an extension of the existing custom module preferences defined under the Global Options component. They will appear in the named Preferences tab and be associated with a Global Variable that will reflect their value. However
1. Game Preferences will NOT be stored in the local preferences file.
2. Their value will be saved as the value of the Global Variable in a save game, and be reset by the value of the Global variable when a save game is loaded.

**Comment by Cattlesquat** [comment]
If you really wanted to bonus it up, it would be glorious if writing to the Global Variable (from elsewhere in the module) updated the preference value.

**Comment by Cattlesquat** [comment]
I've also been racking my brains to think of a way to let stuff in the module know when a custom preference has been changed, without them having to essentially "poll for it". Example application being a preference for light-on-dark or dark-on-light text, changing which TextLabels display on certain pieces. But I haven't thought of anything non-crappy. Best I came up with would be a variant of "Startup Global Key Command" that fired on preference change -- but if one existed & did anything, that would put extra things in the undo stack (for everyone! even though preferences are local!) So that may just be a bridge too far for V3? But it's very sad to have visual display preferences (a prime use case for custom preferences) crippled that way.

**Comment by BrentEaston** [comment]
> I've also been racking my brains to think of a way to let stuff in the module know when a custom preference has been changed, without them having to essentially "poll for it". 

It needs to be built into the custom preference. The preference Configurer and the associated Global Property each have propertyChangeListeners (PCL) that when fired off disable the PCL in the other component and then update it, before re-e
nabling the PCL.

**Comment by BrentEaston** [comment]
> If you really wanted to bonus it up, it would be glorious if writing to the Global Variable (from elsewhere in the module) updated the preference value.

What happens if you write "xyz" to a Global Property that is supposed to be a Boolean Preference?

**Comment by Cattlesquat** [comment]
> What happens if you write "xyz" to a Global Property that is supposed to be a Boolean Preference?

It could just turn that into e.g. false? Or at most chat a Bad Data warning, but I wouldn't waste much effort on that.
