### ISSUE TITLE
DrawPile somehow thinks it doesn't have a map -- [Root by Merk Fixed] NullPointerException: Cannot invoke "VASSAL.build.module.Map.getEdgeBuffer()" because "map" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12008]
| ABR | |
|-----|-----|
| Version | 3.6.11 |
| Reporter |  |
| Error Log | [6570 bytes](https://vassalengine.org/files/gh/299de82d962d703cf94352744f4994c3310206eb) |

<pre>

Root by Merk Fixed v2.5 3.6.11

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.getEdgeBuffer()" because "map" is null
 at VASSAL.build.module.map.SetupStack.setup(SetupStack.java:269)
 at VASSAL.build.module.map.DrawPile.setup(DrawPile.java:1225)
 at VASSAL.build.module.GameState.setup(GameState.java:542)
 at VASSAL.build.module.PredefinedSetup.launch(PredefinedSetup.java:225)
</pre>

**Comment by Cattlesquat** [comment]
The general steps taken, though user  didn't have a reproducible case...

* User was making a new window ("Decree"). 
* Copied/Pasted a deck from another map, into a folder
* Also added a SetupStack or two, but the crash is in DrawPile
* Launched a game using a Predefined Setup (the save for which had apparently not been refreshed since the earth cooled)
