### ISSUE TITLE
Integrate Place Marker trait with Attachment creation / UniquePieceId idea

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12444]
This request addresses the case where Place Marker is used to create a piece that itself needs to maintain communication with the  "parent" piece.  It may also address other situations where the module requires to identify a piece uniquely.

Background: A general design feature affects how the AutoAttach has to be used. An example use-case is the Place Marker trait, where the creating piece (parent) might need to provide a back-link to the created piece (child).  The easy way to do this would be by using Auto() on the created piece, with the same Attachment name configured on the "Parent". However, if multiple instances of the parent exist, the child will acquire links to multiple pieces bearing the same Attachment name, as designed. This will prohibit use of Auto in this case, meaning that a more complex, specifically targeted Attachment trait must be defined. This is more error prone.

**Suggested new feature**:

The Attachment trait could bear another Auto option, specifically to Auto-Attach to a piece that has just used Place Marker or vice-versa. The Auto Attach and/or "When another piece attaches..." options might be models for this feature:
<img width="878" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/798a4dfc-2487-476b-a12d-23b11d6e984c">

**_Alternatively_**, a unique instance id could be made available to the created piece. This idea compromises two parts:

1. A new Piece property,  e.g. `UniquePieceId` that is defined to the instance of that PieceId; this is required because Pieces dragged from a Palette or cloned have identical `PieceId` values.

2. When a Place Marker trait creates a piece, a property `LinkedUniquePieceId` will be defined on both pieces, each to the other piece's `UniquePieceId`.  Obviously this property is transient - it might be overwritten by a future action - but the module developer can deal with that.

The `UniquePieceId` & `LinkedUniquePieceId` properties would allow an Attachment to be created on either piece that will uniquely attach to the target piece. These properties will also be useful for other GKC applications where a specific piece created from a palette needs to be targeted.

**Comment by BrentEaston** [comment]
> A new Piece property, e.g. UniquePieceId that is defined to the instance of that PieceId; this is required because Pieces dragged from a Palette or cloned have identical PieceId values.

This already exists - The property PieceUID returns a unique Id for each piece, as opposed to PieceID which is the same for all pieces created from the same definition.

**Comment by riverwanderer** [comment]
Ah, so it would be helpful to update the reference manual [here](https://vassalengine.org/doc/latest/ReferenceManual/Properties.html) and [here](https://vassalengine.org/doc/latest/ReferenceManual/BasicPiece.html).

**Comment by BrentEaston** [comment]
Thanks Mark, I will try an get an agreement between what I show on the Function Builder menus and what is in the reference manual. I'm going through the code and making sure all appropriate properties are reported by components (and so appear on the Function builder property sub-Menu) and then check they appear in the reference manual as well.

**Comment by BrentEaston** [comment]
Thinking about this further, I think the main piece of the puzzle that is missing, and that would give you the functionality you need is to implement your `LinkedPieceUID` id. With this, you could just use standard auto-attachments and use Attachment based features with additional properties of `{PieceUID == "$LinkedPieceUID$"}. Possibly call it `ParentPieceUID` instead? makes a little more sense.

**Comment by BrentEaston** [comment]
Working with PieceUID is problematic because it is a really large integer, which confuses Vassal. I'm going to add a fix for that, but another problem is that PieceUIDs get re-generated when the Game Refresher runs, so can't be depended upon. My solution is to add two new Piece properties:

 PlaceUID: When a piece first does a Place Marker, placeUID is set to "P" followed by the pieces current PieceUID. 
 ParentPlaceUID: Any piece created by a Place Marker trait gets ParentPlaceUID set to the PieceUID of the piece that created.

You will be able to use {PlaceUID="$ParentPlaceUid$"} to target the parent piece of a placed marker.

**Comment by BrentEaston** [comment]
More thoughts, I have solved the problem with using PieceUID's in expression, so can forget the "P" part,

I think instead of the placeUID idea, I will do the following:
 - Create a new UniqueID property that will be set to PieceUID when the piece is first created and will be preserved across Refreshes. Players will want to use UniqueID for any in-module usage rather that PieceUID and I will update the manual toreflect that.
 - Markers when Places will have a property ParentID that will be set to the UniqueID of the piece that placed it.
 - {UniqueID == "$ParentId$"} will match the parent marker
