### ISSUE TITLE
Integrated Range and Count/  Sum functions

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12445]
Idea is to provide a set of integrated Range and Sum/Count functions, modelled on the By Location category, excluding MapLocation variants:

<img width="669" alt="Sum   Count" src="https://github.com/vassalengine/vassal/assets/58135975/3242b1b9-a53a-4eac-87fb-52a6ea74f8df">

Evaluation would be relative to the location of the piece on which the function is calculated.

Syntax might be along the lines of these examples 

SumRangeInCells(minRange, maxRange, prop)
CountRangeInPixels(minRange, maxRange, expr)
CountRangeInCells(minRange, maxRange, prop, expr)

Use cases based on hexgrid:

Use case 1: Count how many pieces on a hex grid with a property `LDR` are adjacent to the current piece, or colocated:
       `CountRangeInCells(0, 1, "LDR")`

Use case 2:  How many pieces with an `Army` property are in range `Rng` but only opposite side pieces on the Battlefield (Zone property `inBattle`):
   `CountRangeInCells(1, Rng, "Army", "{inBattle && side != \"$side$\"}")`

Use case 3: Is this piece adjacent to a marker of type A or B:
   `CountRangeInCells(1, 1, "{mkrType =~ "\A|B\"}") > 0`

**Comment by BrentEaston** [comment]
Yes, I can see this would be super useful for checking adjacency. And with the new Indexing, they will be super fast.

The full set would be (In the 'Ranged Sum & Count' submenu):

SumRangeInPixels(prop, min, max)
SumRangeInCells(prop,  min, max)
SumRangeInPixels(prop, expr, min, max)
SumRangeInCells(prop, expr, min, max)

CountRangeInPixels(min, max)
CountRangeInCells(min, max)
CountRangeInPixels(prop, min, max)
CountRangeInCells(prop, min, max)
CountRangeInPixels(expr, min, max)
CountRangeInCells(expr, min, max)
CountRangeInPixels(prop, expr, min, max)
CountRangeInCells(prop, expr, min, max)

**Comment by BrentEaston** [comment]
A thought.

In the interested of brevity, I'm wondering whether we get rid of all the InCells/InPixels stuff and just have the basic functions (e.g. SumRange) return in Cells (if possible), but add an optional parameter that you can set to true to force pixels?

SumRange(prop, min, max)
SumRange(prop, min, max, asPixels)
SumRange(prop, expr, min, max)
SumRange(prop, expr, min, max, asPixels)

I would retrofit this to all the Range functions as well. 

Range(attachName)
Range(attachName, asPixels)
Range(x, y)
Range(x, y, asPixels)
etc.

This seems cleaner to me. Most of the time, you are going to want to do Range stuff in Cells, if they exist and if they don't, it uses pixels anyway. It will only occasionally be that you want to do something in pixels on a hex or square grid.

**Comment by riverwanderer** [comment]
Sounds good to me.

**Comment by riverwanderer** [comment]
> SumRange(prop, expr, min, max, asPixels)

It occurs to me that `min, max` are always required, but only one of the preceding fields will be mandatory, to judge from the SumLocation() function. For CountRange(), perhaps neither of `prop` nor `expr` will be required.  Are you thinking that it is better / required to model this new function on Sum() & Count() ? In which case, are `prop` & `expr` always going to be required or can they just be left null ?  e.g. `CountRange(,,0,1)` ?

**Comment by BrentEaston** [comment]
You will be able to just leave out the parameters you don't need, as long as they stay in the correct order, I can work it out. So all of the following are valid and will be available in the Function Builder:

CountRange(0, 1)
CountRange(0, 1, true)
CountRange("Strength", 0, 1)
CountRange("Strength > 2", 0, 100, true)
CountRange("Strength", "Strength > 2", 0, 1)
CountRange("Strength", "Strength > 2", 0, 100, true)

Having said that, I think it makes sense to have the range parameters first, since they are always there, so you get:

CountRange(0, 1)
CountRange(0, 100, true)
CountRange(0, 1, "Strength")
CountRange(0, 100, "{Strength > 2}", true)
CountRange(0, 1, "Strength", "{Strength > 2}")
CountRange(0, 100, "Strength", "{Strength > 2}", true)

Although, does that become confusing when SumRange really needs to have the property first:

SumRange("Str", 0, 1)
SumRange("Str", 0, 100, true)
SumRange("Str", 0, 1, "{Str > 2}")
SumRange("Str", 0, 100, "{Str > 2}", true)

The Function Builder will lead you through this, but I am trying to keeps things reasonable consistent which is why I initially followed the pattern of the existing Sum/Counts and always started with prop, expr,

**Comment by BrentEaston** [comment]
Hmmm.

The 'Must be pixels' versions are going to have to have a different name, otherwise I run into technical problems working out which arguments are which.

CountRange(0, 1)
CountRange(0, 1, "Strength")
CountRange(0, 1, "{Strength > 2}")
CountRange(0, 1, "Strength", "{Strength > 2}")

CountRangeInPixels(0, 100)
CountRangeInPixels(0, 100, "Strength")
CountRangeInPixels(0, 100, "{Strength > 2}")
CountRangeInPixels(0, 100, "Strength", "{Strength > 2}")

SumRange("Str", 0, 1)
SumRange("Str", 0, 1, "{Str > 2}")
SumRangeInPixels("Str", 0, 100)
SumRangeInPixels("Str", 0, 100, "{Str > 2}")

**Comment by riverwanderer** [comment]
Could the cells variant just do without "InCells", since it is the normal usage ?

e.g.  Range() and RangePx()
