### ISSUE TITLE
Does Not Stack with Mouse Over Viewer

### ISSUE THREAD

**Issue by DanielTShaw** [vassalengine/vassal#12495]
I have set Does Not Stack for a piece to
Does Not Move - DOES Stack, Move=NEVER

The properties are:
Select piece normally
Band-Select piece normally
Move  never
Piece can stack normally
Ignore map grid when moving is unchecked

I expected this to mean the piece is included in stacks but does not move.  It does that.

However, the Mouse over viewer does not include this piece. I THINK IT SHOULD.

Attached the module and game save.  The piece the Permanent Fortification in in hex  N4111.
[End_of_Empire_v2-0.zip](https://github.com/vassalengine/vassal/files/12165427/End_of_Empire_v2-0.zip)

**Comment by BrentEaston** [comment]
Thanks Daniel,

I'll have a look at those later today. I did a quick test with a module of mine, but was not able to reproduce it. It might some unusual combination of options;. Thanks very much for providing the module and save game, very helpful.

Regards,
Brent

**Comment by BrentEaston** [comment]
Ok, found the problem.

The unit is not being skipped because it is non-stacking, but because it is non-moveable.

However, the option to show non-moveable pieces doesn't appear unless you first click to include non-stacking pieces.  This is left-over from before 'Do Not Stack' pieces where allowed to Stack.

The work-around is to click 'Include non-stacking', then click 'Include non-moveable', then click 'Include non-stacking' back off. The Non-moveable option stays active, even though it is hidden. This should solve your problem.

For long-term fix, I will separate the 'Include non-moveable' from the 'Include non-stacking' so they can be selected independently.Same issue with the 'Include move-when-selected pieces' option.

**Comment by DanielTShaw** [comment]
If the long term solution is going to take months to fix, I suggest entering a note line onto 
https://vassalengine.org/doc/latest/ReferenceManual/MouseOver.html

**Comment by BrentEaston** [comment]
Fix is already in for the next 3.7 beta and may be back-ported into a future 3.6 release.
