### ISSUE TITLE
Multi-Location Command's exposed properties don't work the first time you try to set a Dyanmic Property

### ISSUE THREAD

**Issue by assaultdoor** [vassalengine/vassal#13449]
I'm trying to set a Dynamic Property to a map name using a Multi-Location Command and the corresponding MapOfCommand property. The first time I do this, it doesn't work. I've tried multiple different ways to access the property: `$MapOfCommand$`, `{MapOfCommand}`, and `{GetProperty("MapOfCommand")}`. I also tried sending the piece a GKC that is ignored and using "Set Dynamic Properties in target pieces" instead. None of these worked the first time. However, if I tried a multi-location command again, it worked fine.

I haven't tested all the other traits, but I know Send to Location and Report Action work fine even when Dynamic Properties can't see the associated properties.

The same issue works for ZoneOfCommand and, I assume the other properties.

I just noticed that setting Global Properties has the same issue.

[testing is slow.zip](https://github.com/user-attachments/files/16120859/testing.is.slow.zip)

This module should illustrate the problem. There is only one piece, and it uses two multi-location commands to try to set four different Dynamic Properties to Test, the name of the only Zone. One command sets the first three dynamic properties using different ways to access the value of ZoneOfCommand (`$ZoneOfCommand`$, `{ZoneOfCommand}`, and `{GetProperty("ZoneOfCommand")}`). The second tries the same with a Global Key Command.

The first time you try one of the commands, ZoneOfCommand does not appear to be a property. The second time you try, whether the second time with the same command or whether you try one of each, works just fine.

**Update:** It looks like Global Properties, Dynamic Properties, and the "Set Dynamic Properties in target pieces" of the Global Key Command are actually getting the values of those properties from the last Multi-Location Command. So, for example, if you first try setting a property to {ZoneOfCommand} when the Zone is "Zone 1," nothing happens. Then you do the same thing, but with "Zone 2," and your property is set to "Zone 2".

**Comment by BrentEaston** [comment]
I believe the problem is that you are trying to initiate multiple traits using the one Key Command. That is not a good technique to use as it is not obvious what order those traits will be executed in, and even if you know what you are doing, you may move the traits around without thinking later and disrupt the order. 

If you want a series of traits to fire off in a specific sequence, then you should ALWAYS start with a Trigger Action that is fired off by the main Key Command and then it fires off all the traits you want in the correct order, using different Key Commands. This will guarantee you correct order of trait execution and is immune to trait order.

If you still have the problem when using a Trigger, I'll look into it further.

Regards.

**Comment by assaultdoor** [comment]
In the original module, I was trying to set a single dynamic property. Connecting it to a Trigger Action or putting it above the Multi-Location Command fixes the issue.
