### ISSUE TITLE
Registered filetypes and associated Icons

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#5963]
| Bugzilla |  |
|----------|----------|
| ID | BZ3931 |
| Reported | 2011-09-13 14:51:00 +0200 |
| Modified | 2020-08-03 22:13:19 +0200 |
| Product | VASSAL |
| Component | Player |
| Version | 3.2.0 |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | enhancement |
| Milestone | 3.2.0 |
| Reporter | [Tim McCarron](mailto:timothy.mccarron@sbcglobal.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |
| CC | brian@brianreynolds.net, timothy.mccarron@sbcglobal.net, uckelman@nomic.net |

#### [Tim McCarron](mailto:timothy.mccarron@sbcglobal.net) 2011-09-13 14:51:54 +0200
<pre>Add and register in system OS the remaining Vassal filetypes and give them Icons (sent to Joel already). Those that need to be done:

vsav
vlog
vmdx
vdck</pre>

#### [Brian Reynolds](mailto:brian@brianreynolds.net) 2020-07-12 21:24:52 +0200
<pre>I dunno what vmdx and vdck are (no existing references to them that I can find anywhere in the code).

But VSAV and VLOG are fully registered. So maybe this got fixed long ago?</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2020-08-03 22:13:19 +0200
<pre>vmdx is for module extensions, vdck was for something to do with saving decks, but I'm not sure that even exists anymore.</pre>

**Comment by Cattlesquat** [comment]
So everything except VMDX seems to already be done, at least on windows.

In fact I can't find where anything _except_ the Windows stuff is done. 

Should we add the VMDX into the windows? Is there anywhere else for other OS to add it? Really if it just had a Vassal icon for the file that would be enough -- no need for any double+click association really (or just start Module Manager) because extensions don't really start by themselves.

**Comment by uckelman** [comment]
An association for VMDX makes little sense, as it needs a module to be opened with.

**Comment by Cattlesquat** [comment]
Okay in that case, this is likely as done as it will ever get even for V4
