### ISSUE TITLE
Add Grid Numbering Dialog blank

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#6130]
| Bugzilla |  |
|----------|----------|
| ID | BZ4193 |
| Reported | 2012-01-06 23:33:00 +0100 |
| Modified | 2020-06-22 00:11:51 +0200 |
| Product | VASSAL |
| Component | Editor |
| Version | 3.1.18 |
| Platform | PC |
| OS | Windows |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | minor |
| Milestone | --- |
| Reporter | [Seth Gilchrist](mailto:irishwulf@gmail.com) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Seth Gilchrist](mailto:irishwulf@gmail.com) 2012-01-06 23:33:37 +0100
<pre>Java 1.6.0_30
SVN 8015
Rectangular grid

Sufficiently large cells (e.g. 300 or so pixels, height or width) cause the Add Grid Numbering dialog to display an empty frame.</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2012-03-04 17:50:32 +0100
<pre>Do you mean that the whole dialog is empty, or just the part displaying the grid numbering?</pre>

#### [Seth Gilchrist](mailto:irishwulf@gmail.com) 2012-03-04 18:53:22 +0100
<pre>(In reply to comment #1)
> Do you mean that the whole dialog is empty, or just the part displaying the
> grid numbering?

The whole dialog.  It looks like an empty JFrame, sized to roughly the dimensions of maybe 2X2 grid cells?</pre>

**Comment by BrentEaston** [comment]
This is being causes because the oversize hexes are causing the visualizer to be huge, which pushes the dialog contents off the right of the screen.

With 3.5.8, there should now be scrollbars on the dialog which allow you to access the rest of the dialog. While not perfect, it does make the dialog usable again.

![image](https://user-images.githubusercontent.com/1622667/128467168-54b1d2c1-2574-4f0e-b067-6efe98e5af27.png)
