### ISSUE TITLE
Inventory trait - Add a Zoom option

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#9366]
| Bugzilla |  |
|----------|----------|
| ID | BZ13566 |
| Reported | 2020-10-28 14:25:00 +0100 |
| Modified | 2020-10-28 14:25:49 +0100 |
| Product | VASSAL |
| Component | Player |
| Version | 3.4.7 |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Claudio Ciardelli](mailto:claudio.ciardelli@gmail.com) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

**Comment by Cattlesquat** [comment]
@claudiociardelli Can you clarify what this would mean/do?

**Comment by Cattlesquat** [comment]
From Claudio -- 

Icons displayed in the Inventory window tend to be very small. There is no way to increase their size. I guess the "zoom" I mention here is more an option to view bigger icons (similar to windows file explore where thumbnails can be seen as small, large or very large images
 
![image](https://user-images.githubusercontent.com/3742246/142057339-310c462b-b26e-48a5-884a-c2174a836ea2.png)

**Comment by Cattlesquat** [comment]
@claudiociardelli So, *super easy* would be a checkbox in the configuration to let the height of each row be determined by the size of the piece's icon (so if when setting the zoom for your piece you picked something 50 pixels high, then that row would be 50 pixels high). It wouldn't be like zooming in the sense that the user would have control of magnifying things on the fly, but it would allow a module designer to designate a comfortable height for everything. 

Adding a line like this into the Inventory's initTreeCellRenderer right after r.height gets determined does that:
`setSize(getWidth(), Math.max(r.height + 2, getHeight()));`

Obviously there'd want to be a checkbox to "opt in" to that in the configurer since otherwise some module designers would be taken very much by surprise.

If we want some kind of dynamic control then we'd need configuration of what the range is (just pop back and forth between two settings like Windows? Zoom continuously over some range? Some arbitrary number of pre-defined zoom settings?) and then buttons/controls to let the user switch between them. None of that is too hard, other than just deciding what it should be and then making some controllers.

**Comment by uckelman** [comment]
It's this going to shove the rows too far apart? I had always thought the point of having the icons was that they're thumbnails---small enough to kind of be identifiable and indicative, but not necessarily large enough to be entirely legible.

**Comment by Cattlesquat** [comment]
It shoves them further apart, but obviously with "good judgment" (I realize sometimes lacking among module designers, but not _universally_ lacking) it's more like, as Claudio says, the different Windows icon views where you can see large or small thumbnails.  Larger thumbnails pushes stuff apart but also makes the icons more readable, and so it ends up being a good tradeoff. 

I suppose we could _define_ the pixel heights we offer (e.g. tiny like currently, and then maybe double & quadruple and octuple or something like that). And then module designer just decides whether to turn all of that on or keep the legacy version.

**Comment by Cattlesquat** [comment]
I'm sure you have something like this in Linux but here is an example of two of my file folders with two very different view and icon sizes.
![image](https://user-images.githubusercontent.com/3742246/142062194-c20a1320-0e51-40be-92cc-034fd72c53ed.png)

**Comment by uckelman** [comment]
I can imagine making the rows taller super annoying if you're trying to use the inventory to find a piece by name. Maybe an additional view is in order?

**Comment by Cattlesquat** [comment]
If we put some kind of flip/flop or 3-way or multi-way control then the user could choose to "zoom in and out" right on the one window. That's probably better than having multiple different windows to have multiple views.

**Comment by Cattlesquat** [comment]
(A question then becomes ... do we let module designer configure how many zoom levels there are and what their respective heights are? Or do we go with a fixed number of zoom levels and _we_ define the allowed column heights)

**Comment by uckelman** [comment]
Yes, some sort of toggle. That's also what file explorers tend to have.

**Comment by uckelman** [comment]
That's why my file explorer has: ![image](https://user-images.githubusercontent.com/442741/142065087-3584c719-b118-4a66-8ca4-3c2e839663dd.png)
The rightmost three icons are "Icon View", "List View", and "Compact View"

**Comment by Cattlesquat** [comment]
Windows has 8 options though many of them relate to column/table views as opposed to just a single column list.

**Comment by uckelman** [comment]
The list view has a bunch of columns showing things like file size and mtime, yeah.

**Comment by Cattlesquat** [comment]
Okay, made 3 levels of zoom. +/- buttons down in the button area. 

![image](https://user-images.githubusercontent.com/3742246/142082758-cc510864-fdb9-469c-af7e-4bc59553c72d.png)
